rem
rem Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
rem All rights reserved.
rem This component and the accompanying materials are made available
rem under the terms of the License "Eclipse Public License v1.0"
rem which accompanies this distribution, and is available
rem at the URL "http://www.eclipse.org/legal/epl-v10.html".
rem
rem Initial Contributors:
rem Nokia Corporation - initial contribution.
rem
rem Contributors:
rem
rem Description:      
rem

@echo off

rem RUNTESTS.BAT
rem
rem Copyright (c) 1997-2000 Symbian Ltd.  All rights reserved.
rem

TGENERALFOREIGN.EXE
TBUILTIN.EXE
TGB2312.EXE
THZ.EXE
TGBK.EXE
TBIG5.EXE
TSHIFTJIS.EXE
TISO2022JP.EXE
TJIS.EXE
TEUCJP_PACKED.EXE
TISO8859X.EXE
TREPLACEMENT.EXE
TSNM.EXE
TAUTODETECT.EXE
TSIMPLE7.EXE
TSIMPLE8.EXE
TRFC1642.EXE
TCOMP7.EXE
TCOMP8.EXE
TREALUT8.EXE
TREALUNI.EXE
TERROR.EXE
TNEWLIN7.EXE
TJAVA.EXE
TPARTIAL.EXE
TIMAP.EXE

